<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Sapiens4</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" /></ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="AppIcon.ico" LogicalName="Sapiens4.AppIcon.Light" />
    <EmbeddedResource Include="AppIconDark.ico" LogicalName="Sapiens4.AppIcon.Dark" />
  </ItemGroup>
  <Target Name="RemoveUnusedWpfWebView" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup><Reference Remove="@(Reference)" Condition="$([System.String]::Copy('%(Filename)').Contains('Microsoft.Web.WebView2.Wpf'))" /></ItemGroup>
  </Target>
</Project>
