const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('web/features/mentions.js','utf8').split('let mentionRange')[0];
const esc = v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sandbox={esc,URL,state:{agents:[{id:'sapi',name:'Nova'}]},mention:id=>`<button>${id}</button>`};
vm.createContext(sandbox);vm.runInContext(source,sandbox);
const render=sandbox.formatText;
let value=render('https://github.com/aleski-green/lab-sapiens-rnd/blob/commit/human_specs/agentpy_spec_human.md');
assert.match(value,/target="_blank"/);assert.match(value,/rel="noopener noreferrer"/);
assert.match(value,/>github.com · agentpy_spec_human.md ↗<\/a>/);
value=render('[Proposal](</Users/Admin/My files/proposal.md>)');
assert.match(value,/data-file-link="\/Users\/Admin\/My files\/proposal.md"/);assert.match(value,/>Proposal<\/button>/);
assert.doesNotMatch(render('@art-md0016 and @art-md0016:old'),/data-artifact-link/);
assert.doesNotMatch(render('@art-md0016:wrong'),/data-artifact-link/);
assert.doesNotMatch(render('@task-x0012 and @create-or-find-one'),/data-task-link/);
assert.doesNotMatch(render('[Bad](javascript:alert(1))'),/<a /);
assert.doesNotMatch(render('<img src=x onerror=alert(1)>'),/<img/);
assert.equal(render('`https://example.com`'),'<code>https://example.com</code>');
assert.match(render('[Reference](https://example.com/docs)'),/>Reference ↗<\/a>/);
assert.match(render('https://example.com/Nova'),/<a /);assert.doesNotMatch(render('https://example.com/Nova'),/<button/);
assert.match(render('https://example.com/a_(b).'),/href="https:\/\/example.com\/a_\(b\)"/);
assert.match(render('**Admin**'),/<strong>Admin<\/strong>/);
const report='/Users/Admin/My files/sapi_team.pdf', citation=`:codex-file-citation{path="${report}" purpose="output"}`;
assert.match(render(citation),/data-file-link="\/Users\/Admin\/My files\/sapi_team.pdf">sapi_team.pdf<\/button>/);
for (const message of [`[PDF](<${report}>) ${citation}`, `${citation}\n\n[PDF](<${report}>)`, `${citation} ${citation}`]) {
  const html=render(message);
  assert.equal((html.match(/data-file-link=/g)||[]).length,1);assert.doesNotMatch(html,/:codex-file-citation/);
}
assert.equal(render('`'+citation+'`'),'<code>'+esc(citation)+'</code>');
assert.equal(render(':codex-file-citation{path="javascript:alert(1)"}'),esc(':codex-file-citation{path="javascript:alert(1)"}'));
assert.equal(render(':codex-file-citation{purpose="output"}'),esc(':codex-file-citation{purpose="output"}'));
assert.match(render(String.raw`:codex-file-citation{purpose="output" path="/tmp/sapi\_team.pdf"}`),/data-file-link="\/tmp\/sapi_team.pdf"/);
assert.match(render(':codex-file-citation{path="file:///tmp/report.pdf"}'),/data-file-link="file:\/\/\/tmp\/report.pdf"/);
assert.doesNotMatch(render(':codex-file-citation{path="/tmp/<img src=x onerror=alert(1)>.pdf"}'),/<img/);
assert.match(render(String.raw`:codex-file-citation{path="/tmp/a\"b.pdf"}`),/data-file-link="\/tmp\/a&quot;b.pdf"/);
sandbox.state.agents.push({id:'retired',name:'Old',retired:true});assert.equal(render('@Old'),'<button>retired</button>');
sandbox.state.agents.push({id:'other',name:'Nova'});assert.equal(render('@Nova'),'@Nova');sandbox.state.agents.pop();
const bridge=fs.readFileSync('web/shell/bridge.js','utf8'), host={innerHTML:'',scrollTop:100,scrollHeight:1000,clientHeight:200,insertAdjacentHTML:(_,s)=>host.innerHTML+=s};
Object.assign(sandbox,{$:()=>host,selected:()=>({id:'sapi'}),getMessages:()=>[{role:'assistant',time:'now',text:`[PDF](<${report}>)\n\n${citation}`}],avatar:()=>'',renderAttachment:()=>{},renderAgentHeader:()=>{},renderGlobal:()=>{},live:{turns:[]},expandedWarnings:new Set(),blocksChat:t=>['queued','running'].includes(t.status),requestStatus:t=>t.status==='failed'?{label:'Failed',detail:t.error}:null,turnActions:()=>'<button>Retry</button>',attachmentLabel:a=>esc(a.name)});
sandbox.state.selected='sapi';sandbox.state.panel='chat';
vm.runInContext(bridge.slice(bridge.indexOf('function renderMessage('),bridge.indexOf('sendChat =')),sandbox);sandbox.renderConversation();
assert.equal((host.innerHTML.match(/data-file-link=/g)||[]).length,1);assert.doesNotMatch(host.innerHTML,/:codex-file-citation/);
host.scrollTop=100;sandbox.renderConversation();assert.equal(host.scrollTop,100);
host.scrollTop=850;sandbox.renderConversation();assert.equal(host.scrollTop,1000);
const request={role:'user',text:'<input>',time:'now',requestTurn:{id:'failed',status:'failed',error:'<failure>'},attachments:[{name:'<report>'}]};
value=sandbox.renderMessage(request,{id:'sapi'});assert.match(value,/>Admin<\/strong>/);assert.match(value,/id="request-failed" hidden/);assert.match(value,/Retry/);assert.match(value,/message-attachments.*&lt;report&gt;/);assert.doesNotMatch(value,/<input>|<failure>/);
sandbox.expandedWarnings.add('request-failed');assert.match(sandbox.renderMessage(request,{id:'sapi'}),/aria-expanded="true"/);
value=sandbox.renderMessage({role:'assistant',text:'partial',warning:'<limit>',turnId:'warn'},{id:'sapi'});assert.match(value,/warning-message/);assert.match(value,/aria-controls="warning-warn"/);assert.match(value,/&lt;limit&gt;/);
Object.assign(sandbox,{renderNotes:h=>h.innerHTML='Notes',activityLog:()=> 'Log'});
for(const panel of ['notes','log','chat']){sandbox.state.panel=panel;sandbox.renderConversation();assert.equal(host.hidden,panel!=='chat');}
console.log('Chat links and local filepath references passed');
sandbox.online=true;
sandbox.live={activity:{sapi:{turn:'current',started:1000,updated:2000,phase:'Waiting for model',last_action:'<completed>'}}};
vm.runInContext(bridge.slice(bridge.indexOf('function turnProgress('),bridge.indexOf('function updateProgress(')),sandbox);
const current={id:'current',agent:'sapi',status:'running',created:new Date(1000).toISOString()};
assert.match(sandbox.turnProgress(current,65000),/Waiting for model · 64s/);
assert.match(sandbox.turnProgress(current,65000),/No recent update · 63s/);
assert.match(sandbox.turnProgress(current,65000),/&lt;completed&gt;/);
assert.doesNotMatch(sandbox.turnProgress({...current,id:'retry'},65000),/completed/);
sandbox.live.activity.sapi.stopping=true;
assert.match(sandbox.turnProgress(current,65000),/Stopping/);
sandbox.online=false;
assert.match(sandbox.turnProgress(current,65000),/Disconnected/);
console.log('Progress, silence, escaping and retry isolation passed');
