const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('web/mentions.js','utf8').split('let mentionRange')[0];
const esc = v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const artifact={type:'artifact',id:'art-md0016',tag:'art-md0016',name:'art-md0016:proposal',owner:'sapi',aliases:['art-md0016:old'],path:'/Users/Admin/My files/proposal.md',url:'/api/agents/sapi/artifacts/proposal.md'};
const sandbox={esc,URL,state:{agents:[{id:'sapi',name:'Nova'}]},live:{artifacts:[artifact],orchestration:{sapi:{tasks:[{id:'task',name:'task-x0012:joke',tag:'task-x0012',aliases:['create-or-find-one']}],past_tasks:[]}}},mention:id=>`<button>${id}</button>`};
vm.createContext(sandbox);vm.runInContext(source,sandbox);
const render=sandbox.formatText;
let value=render('https://github.com/aleski-green/lab-sapiens-rnd/blob/commit/human_specs/agentpy_spec_human.md');
assert.match(value,/target="_blank"/);assert.match(value,/rel="noopener noreferrer"/);
assert.match(value,/>github.com · agentpy_spec_human.md ↗<\/a>/);
value=render('[Proposal](</Users/Admin/My files/proposal.md>)');
assert.match(value,/data-artifact-link="art-md0016"/);assert.match(value,/@art-md0016:proposal/);assert.doesNotMatch(value,/\/Users/);
assert.match(render('@art-md0016 and @art-md0016:old'),/data-artifact-link/);
assert.doesNotMatch(render('@art-md0016:wrong'),/data-artifact-link/);
assert.match(render('@task-x0012 and @create-or-find-one'),/data-task-link/);
assert.doesNotMatch(render('[Bad](javascript:alert(1))'),/<a /);
assert.doesNotMatch(render('<img src=x onerror=alert(1)>'),/<img/);
assert.equal(render('`https://example.com`'),'<code>https://example.com</code>');
assert.match(render('[Reference](https://example.com/docs)'),/>Reference ↗<\/a>/);
assert.match(render('https://example.com/Nova'),/<a /);assert.doesNotMatch(render('https://example.com/Nova'),/<button/);
assert.match(render('https://example.com/a_(b).'),/href="https:\/\/example.com\/a_\(b\)"/);
assert.match(render('**Admin**'),/<strong>Admin<\/strong>/);
console.log('Chat links and artifact mentions passed');
