const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict');
const source=fs.readFileSync('web/features/workspaces.js','utf8').split('async function browserAction')[0];
const state={workspaces:{}};
const context={bootstrap:{preferences:{workspace_revision:2}},state,syncWorkspace:()=>{}};
vm.createContext(context);vm.runInContext(source,context);
context.receiveWorkspaces({workspace_revision:4,workspaces:{a:{tabs:[{id:'new',url:'https://example.org'}]}}});
context.receiveWorkspaces({workspace_revision:3,workspaces:{a:{tabs:[{id:'stale'}]}}});
assert.equal(state.workspaces.a.tabs[0].id,'new');
context.receiveWorkspaces({workspace_revision:5,workspaces:{a:{tabs:[]}}});
assert.equal(state.workspaces.a.tabs.length,0);
assert.equal(context.browserDestination('/Users/My files/notes.md').path,'/Users/My files/notes.md');
assert.equal(context.browserDestination('https://example.com').url,'https://example.com');
assert.equal(context.browserDestination('file:///tmp/a.md').url,'file:///tmp/a.md');
const app=fs.readFileSync('web/shell/app.js','utf8');
vm.runInContext(app.slice(app.indexOf('function syncWorkspace()'),app.indexOf("let search =")),context);
const legacy={id:'blank-a',url:'about:blank'}, file={id:'tab-file',url:'file:///tmp/a.md'}, blank={id:'tab-new',url:'about:blank'};
state.selected='a';state.workspaces.a={tabs:[legacy,file],activeTab:legacy.id};context.syncWorkspace();
assert.deepEqual(Array.from(state.tabs),[file]);assert.equal(state.activeTab,file.id);
state.workspaces.a={tabs:[legacy,file,blank],activeTab:blank.id};context.syncWorkspace();
assert.deepEqual(Array.from(state.tabs),[file,blank]);assert.equal(state.activeTab,blank.id);
state.workspaces.a={tabs:[legacy],activeTab:legacy.id};context.syncWorkspace();assert.equal(state.tabs[0],legacy);
state.workspaces.a={tabs:[]};context.syncWorkspace();assert.equal(state.tabs.length,0);assert.equal(state.activeTab,null);
const sourceAll=fs.readFileSync('web/features/workspaces.js','utf8'), dom={};
context.esc=String;context.$=selector=>dom[selector] ||= {innerHTML:'',setAttribute(k,v){this[k]=v;},querySelector:()=>null};
vm.runInContext(sourceAll.slice(sourceAll.indexOf('const bookmarks ='),sourceAll.indexOf('function renderWorkspace()')),context);
Object.assign(context.$('#browser-tabs'),{clientWidth:200,scrollWidth:400,children:[]});
state.workspaces.a={tabs:[file,blank],activeTab:file.id,bookmarks:[{id:'saved',url:file.url}]};context.renderTabs();
assert.equal(dom['#browser-overflow'].hidden,false);assert.equal(dom['#browser-overflow'].textContent,'› 2');
assert.match(dom['#browser-tabs'].innerHTML,/aria-pressed="true"[^>]*>★/);assert.match(dom['#browser-all-tabs'].innerHTML,/Open tabs · 2/);
assert.match(dom['#browser-bookmarks'].innerHTML,/data-bookmark-open="file:\/\/\/tmp\/a.md"/);
dom['#browser-tabs'].clientWidth=500;context.layoutTabs();assert.equal(dom['#browser-overflow'].hidden,true);
const rows=[{},{},{}];Object.assign(dom['#browser-tabs'],{clientWidth:300,children:rows,querySelector:()=>rows[2]});
context.layoutTabs();assert.deepEqual(rows.map(r=>r.hidden),[false,true,false]);
const duplicate={...file,id:'fourth'}, preceding=[file,{id:'second',url:'https://two.test'},{id:'third',url:'https://three.test'}];
state.workspaces.a={tabs:[...preceding,duplicate],activeTab:duplicate.id,bookmarks:[{id:'saved',url:file.url,tab_id:duplicate.id}]};context.renderTabs();
assert.deepEqual([...dom['#browser-all-tabs'].innerHTML.matchAll(/data-star-tab="([^"]+)" aria-label="[^"]*" aria-pressed="([^"]+)"/g)].map(m=>[m[1],m[2]]),[...preceding.map(t=>[t.id,'false']),[duplicate.id,'true']]);
assert.ok(dom['#browser-tabs'].innerHTML.indexOf('data-star-tab="fourth"')<dom['#browser-tabs'].innerHTML.indexOf('data-star-tab="tab-file"'));
state.workspaces.a.bookmarks=[];context.renderTabs();assert.doesNotMatch(dom['#browser-all-tabs'].innerHTML,/>★/);
state.workspaces.a.bookmarks=[{id:'legacy',url:file.url}];context.renderTabs();assert.equal((dom['#browser-all-tabs'].innerHTML.match(/>★/g)||[]).length,1);
state.workspaces.a.bookmarks[0].tab_id=duplicate.id;state.workspaces.a.tabs=preceding;context.renderTabs();assert.match(context.starButton(file),/>★/);
console.log('Browser revisions and destinations passed');
