const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict');
const source=fs.readFileSync('web/workspaces.js','utf8').split('async function browserAction')[0];
const state={workspaces:{}};
const context={bootstrap:{preferences:{workspace_revision:2}},state,syncWorkspace:()=>{}};
vm.createContext(context);vm.runInContext(source,context);
context.receiveWorkspaces({workspace_revision:4,workspaces:{a:{tabs:[{id:'new',url:'https://example.org'}]}}});
context.receiveWorkspaces({workspace_revision:3,workspaces:{a:{tabs:[{id:'stale'}]}}});
assert.equal(state.workspaces.a.tabs[0].id,'new');
context.receiveWorkspaces({workspace_revision:5,workspaces:{a:{tabs:[]}}});
assert.equal(state.workspaces.a.tabs.length,0);
assert.equal(context.browserDestination('/Users/My files/notes.md').path,'/Users/My files/notes.md');
assert.equal(context.browserDestination('https://example.com').url,'https://example.com');
assert.equal(context.browserDestination('file:///tmp/a.md').url,'file:///tmp/a.md');
console.log('Browser revisions and destinations passed');
